### PR TITLE
[WIP] run tests in node without spinning up a browserwindow

### PR DESCRIPTION
**Pull request by JM-Mendez**
The main purpose of a custom runner for electron (correct me if I'm wrong), is to test against electron's version of node for native modules.

I don't always need to test native modules or a browser environment, and test runs using a browserwindow are significantly slower than running under node (about 2x). Which is similar to using the default jsdom environment.

This PR allows punting to jest's node environment when set with the docblock tag per test file, matching the jest api.
```
/**
 * @jest-environment node
 */
```
The default environment is the one provided by the jest configuration file.

I was able to see the following performance improvement, which were fairly consistent across multiple test runs:

electron runner
screenshot 2018-12-17 23 34 39

node
screenshot 2018-12-17 23 33 14

If there's anything I overlooked, let me know.

Todo:
- [ ] tests for docblock logic

### CODE REVIEW

**Comment by boujeepossum** [comment]
hey @JM-Mendez!
my initial goal for this runner was actually to run tests using real DOM and also test APIs in browser processes (specifically Atom and Nuclide APIs), but it seems like running tests in the node process is also a thing that people need :)
i really like the idea of using the directive to determine where to run tests, but unfortunately this implementation breaks the isolation of tests, since node tests will now share the same process and could affect each other when run concurrently.
ideally we should use the same architecture regular jest runner uses, which is spawning N separate processes and running only maximum 1 tests in 1 process at a time

**Comment by JM-Mendez** [comment]
Yeah, I was actually working on just that at the moment. I'm debating three alternatives:

1. defer to `jest-runner` if node is requested
2. spin up N processes using `jest-worker` under the current node process
3. use the spawned electron node instance, and then spin up N processes from there

I've tried a dirty hack of (1), but the tests seem to be just as slow as using jsdom at times. It's random enough to give me no hint as to why.

I'm leaning away from (2), and more towards (3) since then we'd be using the node binary used by electron.

@aaronabramov do you have any preference or suggestions?

**Comment by boujeepossum** [comment]
if we're keeping a single runner for both scenarios, i'd say..
first let me define things to not get confused  😛

TestRunner - class responsible for scheduling and running tests (e.g. `packages/electron/src/TestRunner.js`)
Electron main process - the node environment of electron
Electron binary - `electron` that we spawn, that starts electron main process by default
Browser process - the process we start when we run `new BrowserWindow`


to be able to run tests in both environment i'd see it this way.

# 1st option
1. by default everything is run in browser processes, the same way it works now
2. if we want to run it in main process we use `@jest-electron-runner-environment main` (i wouldn't reuse @jest-environment, cause technically it's not the environment)
3. when we start TestRunner we automatically spawn one electron binary that gives us one electron main process that we'll only use to run tests in the browser environment (same as it works now)
4. before we run every test we parse its docblock of the test (in the TestRunner class) and if `@jest-electron-runner-environment main` is found we request another spawned electron binary process from the pool of processes.

img_0349


This make things pretty complicated though, because we're forcing one TestRunner class to do two separate things :)
# 2nd option
for cleanness we might want to just build another test runner that runs it in main process and not try to reuse the same runner.
it'll make configuration harder, but the design simpler.

e.g.
```js
// jest.config.js
module.exports = {
  ...
  projects: ['main-process.config.js', 'browser-process.config.js'],
}
```
```js
// main-process.config.js

module.exports = {
  testMatch: ['**/__main_process_tests_/**'],
  runner: '@jest-runner/electron/main',
}

// browser-process.config.js
// ...
```
img_0350

**Comment by JM-Mendez** [comment]
Wow! This is amazingly helpful. 

Personally, I'm really digging the isolation and simplicity of option 2. It also gives the user the option to separate tests in 3 parts, while letting us only maintain 2 logic flows: 
 
 - browser tests
 - main process tests (electron and native modules)
 - standard node tests

Loading up the browser environment has been what's slowing tests down, and I'm not sure how performant spinning up new electron binaries would be. But for a project like mine where I'm testing plain functions and don't need the browser or main process, I could drop back into jest node testing.

I'll also look into hiding the electron dock/taskbar icons, or else I think there would be N icons launched.

I'll start experimenting with option 2 for the time being.

**Comment by boujeepossum** [comment]
> how performant spinning up new electron binaries would be.

it might take a while to start the process, but as long as they can be reused it shouldn't be bad.
as an optimization these processes could start before we even have any tests to run, so by the time we create a list of tests we already have hot electron processes waiting for input.

having a process poll is probably the hardest part, i wish `jest-worker` had an option to specify a custom binary that it can run :( maybe there's another package that can do that.

also it'll probably need a separate RPC module, check out https://github.com/facebook-atom/jest-electron-runner/blob/master/package.json#L45 
this is where rpc clients are generated. it's a super simple implementation of typed IPC 
https://github.com/facebook-atom/jest-electron-runner/blob/master/packages/rpc/__tests__/simple_rpc.test.js

also, thank you so much for looking into it!

**Comment by JM-Mendez** [comment]
> having a process poll is probably the hardest part, i wish jest-worker had an option to specify a custom binary that it can run :( maybe there's another package that can do that.

I agree. This is where I'm stuck at for now. What if the worker file that `jest-worker` launches spawns a new binary? I'm not sure how persistent the processes are though, and whether we could reuse them. My guess is yes, since the readme says it reuses processes when it can.

> also it'll probably need a separate RPC module

~Correct me if I'm wrong, but we shouldn't need the RPC module when running tests in the main process. From the looks of it, it seems that the purpose of this module is to communicate with the renderer process and run the tests in that environment.~

Nevermind, I just realized that it will need it's own RPC module.

> also, thank you so much for looking into it!

No, thank you for helping me contribute. I've been looking for a project to get involved in since I started programming 2 years ago. And your help has already been tremendous. :)

**Comment by boujeepossum** [comment]
> What if the worker file that jest-worker launches spawns a new binary? 

that could work! if you cache and reuse spawned electron process. there's a bit of complexity though as well, since you're going to need to IPCs, but that should be ok for now.

> Correct me if I'm wrong, but we shouldn't need the RPC module when running tests in the main process. From the looks of it, it seems that the purpose of this module is to communicate with the renderer process and run the tests in that environment.

you'll need to have some kind of RPC communication. `jest-worker` provides you a nice API that you can use to call to node processes, but you still need something to make communication between `jest-worker.js` and `/bin/electron` processes 
img_0353

**Comment by JM-Mendez** [comment]
Ok, so I don't think we'll be able to use `jest-worker` or something similar. It keeps spawning subprocesses and not reusing the previous ones. I also tried with `general-pool`, but no luck. I think it has to do with the fact we're spawning detached child processes. I'm not sure tho.

The good news is that spinning up the electron binary is pretty quick. I only saw an increase of ~1 sec on my test runs, which is comparable to running it with vanilla node. So personally I'll take that. Plus, `throat` will never run more tests than required, so I chose the approach of killing the spawned process after each test file is run.

The change was simple enough to be incorporated into the original `TestRunner` module, but I left it separated since it adheres closer to the electron mindset of two separate processes. 

In the end it ended up being mostly a copy/paste job, and I'm not sure how much duplication you're comfortable with. So if you prefer to keep it in the same module, I can do that and then just use docblock tags to separate the logic flow.

I also work exclusively with typescript and don't know how to properly setup a flow work env, so I was shooting blind on types. That and tests I'll most likely need a little bit more guidance as they're very foreign to me (especially the fiddle)

Commit below:
https://github.com/JM-Mendez/jest-electron-runner/tree/separate-main-renderer

If you're on macOs and want to see the process icons in the dock, you'll have to comment out this line: [`app.dock.hide()`](https://github.com/JM-Mendez/jest-electron-runner/blob/edf2c83608a3f2c7f23d84cfefc5e5f97fdfc082/packages/electron/src/electron_process_injected_code_main.js#L23). That way you can verify that each test is in fact isolated if you want.

EDITS: 
 - link to code line
 - closing this implementation and moving to other branch (or should I push changes here?)

**Comment by boujeepossum** [comment]
@JM-Mendez spawning processes every time sounds like a good idea if it's still fast.
the lint to the commit you gave is returning 404, i assume you were talking about this commit? https://github.com/JM-Mendez/jest-electron-runner/commit/964c03730ebc8b25c32a3813cd8f9f885907b9b8

there's definitely a lot of duplication and we should try to share thing as much as possible.
maybe create a base class and two subclasses?

and also, i've been wanting to try typescript for a while, how hard do you think it would be to transform this codebase to typescript? 😛

**Comment by JM-Mendez** [comment]
Yeah, sorry about the bad link. I had pushed a fix commit and didn't update the link. You saw the right one though.

> there's definitely a lot of duplication and we should try to share thing as much as possible.
maybe create a base class and two subclasses?

This sounds good. I'll get right on it within the next couple of days and merge those changes into this branch.

I also think we should name the environment `node` instead of `main`, since this refactor allows isolating browser and non-browser related code. Thoughts?

> and also, i've been wanting to try typescript for a while, how hard do you think it would be to transform this codebase to typescript?

I don't claim to be a typescript expert, but I think I can manage this. My dev env is already set up for typescript and I can read flow types. My main issue was not getting any IDE support for flow (and I need the crutches lol).

I'll branch off from the refactored codebase and start an experimental typescript directory for this.

**Comment by boujeepossum** [comment]
> I also think we should name the environment node instead of main

https://electronjs.org/docs/tutorial/application-architecture

calling it "node" is pretty ambiguous, cause both processes have node APIs available :)
since the architecture clearly defines `main process` and `renderer process` i think it's a good idea to call them the same.

so for configuration it'll be

```js
    {
      // ...
      runner: '@jest-runner/electron/renderer',
      testEnvironment: '@jest-runner/electron/environment/renderer',
    }

// or

    {
      // ...
      runner: '@jest-runner/electron/main',
      testEnvironment: '@jest-runner/electron/environmen/maint',
    }
```

with a default set to renderer, maybe?

so
```js
    {
      // ...
      runner: '@jest-runner/electron',
      testEnvironment: '@jest-runner/electron/environment',
    }
```

will be the same as `@jest-runner/elector/renderer`

**Comment by JM-Mendez** [comment]
> calling it "node" is pretty ambiguous, cause both processes have node APIs available :)

This makes perfect sense. 

I also think that setting the default to `renderer` is a good idea. This would be a breaking change tho, but I suppose I could add some sort of migration strategy and deprecation notice? I'm new to all this so not sure the best way forward.

Can you also explain the purpose of `testEnvironment`? It looks like its main job is to clean up between tests, but since we're spinning up new processes, I don't think we need it. Am I wrong?

**Comment by boujeepossum** [comment]
> I also think that setting the default to renderer is a good idea. This would be a breaking change tho, 

it shouldn't be breaking because the current default setting (and only one) uses renderer process. so nothing gonna change for that :)
you're just adding the alias to `@jest-runner/electron/renderer` and another runner `@jest-runner/electron/main`

> Can you also explain the purpose of testEnvironment?

it doesn't do much, bet it's required by `jest` and i don't think the default environment works with electron, so i had to create a separate module for it

**Comment by JM-Mendez** [comment]
I merged the updated changes into this branch in order to preserve comment history. The code works, but I still have to look into why some tests fail. 

There is one specific test that fails with type checking with  `Cannot call 'this.cleanup' because property 'cleanup' is missing in 'TestRunnerBase'` or similar. This is due to my lack of knowledge with flow. 

My intention was to make the base class an abstract class so that I can call some methods on it's subclasses. In typescript I'd use an abstract class type. I haven't figured out how to do it with flow, but if you want the next release to include typescript then it won't be necessary.

**Comment by aaronabramov** [comment]
hey @JM-Mendez ! i'm fixing the types/lints right now, and trying to reduce some duplication. do you have email/slack/messenger? :)

**Comment by JM-Mendez** [comment]
> do you have email/slack/messenger? :)

I have slack, but I don't really use it since I'm a solo dev. But I don't mind downloading or installing any other messenger. Or you can email me at john.manuel.mendez@gmail.com Whatever works for you.

**Comment by JM-Mendez** [comment]
Oh, and I pushed some changes before you commented that fixed those errors.

**Comment by boujeepossum** [comment]
manually merged to master

**Pull request closed without merging**
