### PR TITLE
Updates commandLine switches to occur before app start

### PR DESCRIPTION
**Pull request by smacpherson64**
Updates the commandLine switches to occur before the app start so they can take effect.

### CODE REVIEW

**Comment by boujeepossum** [comment]
thanks!

**Comment by smacpherson64** [comment]
Hey @aaronabramov! Sorry to ask! Is it possible to publish this change to npm?

**Comment by boujeepossum** [comment]
oh no. i didn't realize i didn't publish it. i'll do it right now
sorry about that @smacpherson64

**Comment by smacpherson64** [comment]
No worries at all, thank you!

**Comment by boujeepossum** [comment]
`@jest-runner/electron@2.0.3`

**Pull request merged**
