### PR TITLE
rpc: Bump jscodeshift@0.6.3

### PR DESCRIPTION
**Pull request by rajivshah3**
Bumps [jscodeshift](https://github.com/facebook/jscodeshift) to 0.6.3, fixing a ReDoS [vulnerability](https://app.snyk.io/test/npm/@jest-runner/rpc/1.0.2) in `braces` (an indirect dependency)

### CODE REVIEW

**Comment by boujeepossum** [comment]
thanks @rajivshah3!

**Comment by rajivshah3** [comment]
Thanks for merging @aaronabramov ! If it's not too much trouble, would you be able to create a new release? We plan to add `@jest-runner/electron` to our project soon but the Snyk dependency check is failing because of the `braces` issue: https://app.snyk.io/test/npm/@jest-runner/electron/1.0.3

**Comment by boujeepossum** [comment]
@rajivshah3 sorry, missed this email.
i'll do a release tomorrow!

**Comment by rajivshah3** [comment]
Thanks!

**Comment by boujeepossum** [comment]
@rajivshah3 published `1.1.0` https://www.npmjs.com/package/@jest-runner/electron

**Pull request merged**
